name = ZhiShiFan 
title = 芝士蕃
description = 玩中学，一起遨游在知识的海洋中！ 
allowed_mapgens = singlenode, flat
disabled_settings = enable_server, !enable_damage
textdomain = zsf_game_meta
author = NonePro 
release = 23457 